In [1]:
import pandas as pd
import numpy as np
import joblib
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler,PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.linear_model import SGDRegressor

In [2]:
df = pd.read_csv(r"C:\Users\udays\Documents\Mercedes\Model\mercedes_benz_sales.csv")

In [3]:
df.head()

,Model,Year,Region,Color,Fuel Type,Base Price (USD),Horsepower,Sales Volume,Turbo
0,A-Class,2020,Global,Yellow,Diesel,41265,252,1,Yes
1,A-Class,2020,Global,Black,Petrol,51023,249,1,No
2,A-Class,2020,Global,Grey,Petrol,72819,341,1,Yes
3,A-Class,2020,Global,Black,Petrol,62480,385,1,Yes
4,A-Class,2020,Global,White,Petrol,35189,337,1,Yes

In [4]:
df.shape

(12132666, 9)

In [5]:
df.describe()

               Year  Base Price (USD)    Horsepower  Sales Volume
count  1.213267e+07      1.213267e+07  1.213267e+07    12132666.0
mean   2.022548e+03      1.042169e+05  3.674594e+02           1.0
std    1.658896e+00      6.783388e+04  1.195446e+02           0.0
min    2.020000e+03      3.500000e+04  1.500000e+02           1.0
25%    2.021000e+03      6.346200e+04  2.750000e+02           1.0
50%    2.023000e+03      8.357200e+04  3.580000e+02           1.0
75%    2.024000e+03      1.199200e+05  4.440000e+02           1.0
max    2.025000e+03      4.112460e+05  8.310000e+02           1.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12132666 entries, 0 to 12132665
Data columns (total 9 columns):
 #   Column            Dtype
---  ------            -----
 0   Model             object
 1   Year              int64
 2   Region            object
 3   Color             object
 4   Fuel Type         object
 5   Base Price (USD)  int64
 6   Horsepower        int64
 7   Sales Volume      int64
 8   Turbo             object
dtypes: int64(4), object(5)
memory usage: 833.1+ MB

In [7]:
cat_col = df.select_dtypes(include=["object"]).columns

In [8]:
for col in cat_col:
    print(f"{col} : {df[col].unique()}")

Model : ['A-Class' 'C-Class' 'E-Class' 'S-Class' 'CLA' 'CLS' 'GLA' 'GLB' 'GLC'
 'GLE' 'GLS' 'G-Class' 'AMG GT' 'AMG A 45' 'AMG C 63' 'AMG E 63'
 'AMG S 63']
Region : ['Global']
Color : ['Yellow' 'Black' 'Grey' 'White' 'Silver' 'Brown' 'Blue' 'Red' 'Green'
 'Orange']
Fuel Type : ['Diesel' 'Petrol' 'Hybrid' 'Electric']
Turbo : ['Yes' 'No']

In [9]:
df = df.loc[:,df.nunique()>1]

In [10]:
df.head()

     Model  Year   Color Fuel Type  Base Price (USD)  Horsepower Turbo
0  A-Class  2020  Yellow    Diesel             41265         252   Yes
1  A-Class  2020   Black    Petrol             51023         249    No
2  A-Class  2020    Grey    Petrol             72819         341   Yes
3  A-Class  2020   Black    Petrol             62480         385   Yes
4  A-Class  2020   White    Petrol             35189         337   Yes

In [11]:
df.nunique()

Model                   17
Year                     6
Color                   10
Fuel Type                4
Base Price (USD)    366227
Horsepower             682
Turbo                    2
dtype: int64

In [12]:
X = df.drop(columns=["Base Price (USD)"])
y = df["Base Price (USD)"]

In [ ]:
X_trainval,X_test,y_trainval,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [14]:
X_train,X_val,y_train,y_val = train_test_split(X_trainval,y_trainval,test_size=0.25,random_state=42)

In [15]:
X_train["Model"].unique()

array(['E-Class', 'GLA', 'C-Class', 'GLC', 'GLS', 'A-Class', 'GLB', 'CLA',
       'G-Class', 'S-Class', 'GLE', 'AMG E 63', 'AMG C 63', 'AMG A 45',
       'CLS', 'AMG GT', 'AMG S 63'], dtype=object)

In [15]:
X_train.head()

            Model  Year   Color Fuel Type  Horsepower Turbo
6528692   E-Class  2023  Silver    Diesel         485   Yes
11172239      GLA  2025   Black    Hybrid         220   Yes
4217031   C-Class  2022  Yellow    Petrol         327   Yes
4136543   C-Class  2022  Orange    Diesel         319   Yes
9643857       GLC  2024    Grey    Hybrid         208   Yes

In [16]:
ohe_encoder = Pipeline([ ("ohe_encoding",OneHotEncoder(drop="first",handle_unknown = "ignore")) ])
numeric_pipe = Pipeline([
    ("polynomial",PolynomialFeatures(degree=2,include_bias=False)),
    ("Scale",StandardScaler())
])

In [18]:
col = ColumnTransformer(transformers=[
    ("OHE",ohe_encoder,["Model","Color","Fuel Type","Turbo"]),
    ("Numeric",numeric_pipe,["Horsepower","Year"])
],remainder="passthrough")

In [19]:
model = Pipeline(steps=[
    ("preprocessing",col),
    ("model",SGDRegressor(
        loss="squared_error",
        penalty="l2",
        alpha = 0.0001,
        eta0=0.1,
        max_iter = 1000,
        early_stopping = True,
        learning_rate = "adaptive",
        random_state=42,
        verbose = 1
    ))
])

In [20]:
model.fit(X_train,y_train)

-- Epoch 1
Norm: 557879.96, NNZs: 34, Bias: 70870.393964, T: 6551639, Avg. loss: 1998750939.198111
Total training time: 6.28 seconds.
-- Epoch 2
Norm: 519709.90, NNZs: 34, Bias: 71338.814824, T: 13103278, Avg. loss: 1874128219.962757
Total training time: 13.14 seconds.
-- Epoch 3
Norm: 562921.81, NNZs: 34, Bias: 68907.015494, T: 19654917, Avg. loss: 1997757150.784433
Total training time: 19.59 seconds.
-- Epoch 4
Norm: 529796.55, NNZs: 34, Bias: 70328.019028, T: 26206556, Avg. loss: 1855193658.187289
Total training time: 26.48 seconds.
-- Epoch 5
Norm: 518878.44, NNZs: 34, Bias: 71155.132912, T: 32758195, Avg. loss: 1949465220.259533
Total training time: 33.27 seconds.
-- Epoch 6
Norm: 495031.90, NNZs: 34, Bias: 68793.716803, T: 39309834, Avg. loss: 2022457044.216025
Total training time: 40.25 seconds.
-- Epoch 7
Norm: 527888.97, NNZs: 34, Bias: 68998.741274, T: 45861473, Avg. loss: 595479030.810331
Total training time: 47.30 seconds.
-- Epoch 8
Norm: 518100.40, NNZs: 34, Bias: 68892.681780, T: 52413112, Avg. loss: 594995429.497654
Total training time: 54.24 seconds.
-- Epoch 9
Norm: 529165.06, NNZs: 34, Bias: 68951.014048, T: 58964751, Avg. loss: 595074024.460577
Total training time: 61.36 seconds.
-- Epoch 10
Norm: 511709.18, NNZs: 34, Bias: 69111.297659, T: 65516390, Avg. loss: 595388314.753810
Total training time: 68.45 seconds.
-- Epoch 11
Norm: 520542.78, NNZs: 34, Bias: 69257.884509, T: 72068029, Avg. loss: 595385202.088165
Total training time: 75.41 seconds.
-- Epoch 12
Norm: 516672.48, NNZs: 34, Bias: 70110.637483, T: 78619668, Avg. loss: 595257594.880831
Total training time: 82.45 seconds.
-- Epoch 13
Norm: 522021.80, NNZs: 34, Bias: 69462.332167, T: 85171307, Avg. loss: 595311982.480910
Total training time: 89.50 seconds.
-- Epoch 14
Norm: 514632.11, NNZs: 34, Bias: 69593.908806, T: 91722946, Avg. loss: 595130471.998345
Total training time: 96.90 seconds.
-- Epoch 15
Norm: 527973.73, NNZs: 34, Bias: 69565.904249, T: 98274585, Avg. loss: 595270681.766718
Total training time: 103.85 seconds.
-- Epoch 16
Norm: 523328.53, NNZs: 34, Bias: 69501.706819, T: 104826224, Avg. loss: 595174852.850203
Total training time: 110.87 seconds.
-- Epoch 17
Norm: 525316.35, NNZs: 34, Bias: 70088.013106, T: 111377863, Avg. loss: 595187485.955855
Total training time: 117.90 seconds.
-- Epoch 18
Norm: 520052.53, NNZs: 34, Bias: 69117.994906, T: 117929502, Avg. loss: 595329173.270395
Total training time: 124.91 seconds.
-- Epoch 19
Norm: 510278.18, NNZs: 34, Bias: 68839.439324, T: 124481141, Avg. loss: 595617399.933715
Total training time: 131.92 seconds.
-- Epoch 20
Norm: 516828.04, NNZs: 34, Bias: 69491.941905, T: 131032780, Avg. loss: 536234921.816473
Total training time: 138.76 seconds.
-- Epoch 21
Norm: 517758.37, NNZs: 34, Bias: 69731.166006, T: 137584419, Avg. loss: 536247561.840496
Total training time: 145.15 seconds.
-- Epoch 22
Norm: 518115.20, NNZs: 34, Bias: 69627.173558, T: 144136058, Avg. loss: 536180932.288092
Total training time: 151.99 seconds.
-- Epoch 23
Norm: 519811.27, NNZs: 34, Bias: 69335.083750, T: 150687697, Avg. loss: 536309721.364112
Total training time: 159.03 seconds.
-- Epoch 24
Norm: 518382.75, NNZs: 34, Bias: 69682.814614, T: 157239336, Avg. loss: 536301389.060227
Total training time: 166.00 seconds.
-- Epoch 25
Norm: 519796.53, NNZs: 34, Bias: 69616.530217, T: 163790975, Avg. loss: 526188382.912070
Total training time: 172.98 seconds.
-- Epoch 26
Norm: 519178.08, NNZs: 34, Bias: 69533.061603, T: 170342614, Avg. loss: 526152353.456622
Total training time: 179.90 seconds.
-- Epoch 27
Norm: 520865.69, NNZs: 34, Bias: 69597.866162, T: 176894253, Avg. loss: 526226327.113276
Total training time: 186.91 seconds.
-- Epoch 28
Norm: 521337.06, NNZs: 34, Bias: 69601.951162, T: 183445892, Avg. loss: 526204250.279242
Total training time: 193.91 seconds.
-- Epoch 29
Norm: 521089.63, NNZs: 34, Bias: 69566.571478, T: 189997531, Avg. loss: 526221588.010444
Total training time: 200.93 seconds.
-- Epoch 30
Norm: 520859.52, NNZs: 34, Bias: 69573.141576, T: 196549170, Avg. loss: 524235096.703212
Total training time: 207.90 seconds.
-- Epoch 31
Norm: 520727.71, NNZs: 34, Bias: 69563.847959, T: 203100809, Avg. loss: 524236366.223873
Total training time: 214.90 seconds.
-- Epoch 32
Norm: 520044.87, NNZs: 34, Bias: 69562.093870, T: 209652448, Avg. loss: 524239382.170342
Total training time: 221.83 seconds.
-- Epoch 33
Norm: 520557.51, NNZs: 34, Bias: 69565.848425, T: 216204087, Avg. loss: 524235583.740408
Total training time: 228.85 seconds.
-- Epoch 34
Norm: 520510.84, NNZs: 34, Bias: 69561.217724, T: 222755726, Avg. loss: 524225621.168809
Total training time: 235.26 seconds.
-- Epoch 35
Norm: 520719.80, NNZs: 34, Bias: 69566.420029, T: 229307365, Avg. loss: 523854811.114039
Total training time: 242.27 seconds.
-- Epoch 36
Norm: 520635.32, NNZs: 34, Bias: 69565.991755, T: 235859004, Avg. loss: 523855140.953224
Total training time: 249.37 seconds.
-- Epoch 37
Norm: 520801.32, NNZs: 34, Bias: 69567.021936, T: 242410643, Avg. loss: 523848618.502685
Total training time: 256.23 seconds.
-- Epoch 38
Norm: 520492.36, NNZs: 34, Bias: 69562.374068, T: 248962282, Avg. loss: 523852860.336481
Total training time: 263.23 seconds.
-- Epoch 39
Norm: 520437.68, NNZs: 34, Bias: 69562.639926, T: 255513921, Avg. loss: 523850337.355935
Total training time: 270.05 seconds.
-- Epoch 40
Norm: 520527.68, NNZs: 34, Bias: 69562.344494, T: 262065560, Avg. loss: 523781929.448873
Total training time: 277.07 seconds.
-- Epoch 41
Norm: 520607.75, NNZs: 34, Bias: 69563.383173, T: 268617199, Avg. loss: 523777402.390960
Total training time: 284.04 seconds.
-- Epoch 42
Norm: 520606.00, NNZs: 34, Bias: 69564.327285, T: 275168838, Avg. loss: 523774378.189316
Total training time: 290.96 seconds.
-- Epoch 43
Norm: 520606.55, NNZs: 34, Bias: 69563.983332, T: 281720477, Avg. loss: 523774928.422918
Total training time: 297.90 seconds.
-- Epoch 44
Norm: 520608.38, NNZs: 34, Bias: 69564.279666, T: 288272116, Avg. loss: 523774457.027490
Total training time: 304.61 seconds.
-- Epoch 45
Norm: 520615.17, NNZs: 34, Bias: 69564.210602, T: 294823755, Avg. loss: 523756901.409297
Total training time: 311.39 seconds.
-- Epoch 46
Norm: 520611.73, NNZs: 34, Bias: 69563.714187, T: 301375394, Avg. loss: 523756239.703213
Total training time: 318.48 seconds.
-- Epoch 47
Norm: 520615.70, NNZs: 34, Bias: 69564.002838, T: 307927033, Avg. loss: 523754929.904869
Total training time: 325.48 seconds.
-- Epoch 48
Norm: 520613.14, NNZs: 34, Bias: 69563.577120, T: 314478672, Avg. loss: 523756225.213088
Total training time: 332.51 seconds.
-- Epoch 49
Norm: 520612.61, NNZs: 34, Bias: 69563.510848, T: 321030311, Avg. loss: 523754913.513815
Total training time: 339.45 seconds.
-- Epoch 50
Norm: 520615.63, NNZs: 34, Bias: 69563.792661, T: 327581950, Avg. loss: 523751937.978441
Total training time: 346.42 seconds.
-- Epoch 51
Norm: 520615.86, NNZs: 34, Bias: 69563.835586, T: 334133589, Avg. loss: 523751922.241809
Total training time: 353.43 seconds.
-- Epoch 52
Norm: 520615.80, NNZs: 34, Bias: 69563.840211, T: 340685228, Avg. loss: 523751875.759448
Total training time: 360.03 seconds.
-- Epoch 53
Norm: 520616.60, NNZs: 34, Bias: 69563.835455, T: 347236867, Avg. loss: 523751582.425524
Total training time: 367.04 seconds.
-- Epoch 54
Norm: 520615.74, NNZs: 34, Bias: 69563.788820, T: 353788506, Avg. loss: 523751991.251822
Total training time: 373.84 seconds.
Convergence after 54 epochs took 373.91 seconds

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('OHE',
                                                  Pipeline(steps=[('ohe_encoding',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore'))]),
                                                  ['Model', 'Color',
                                                   'Fuel Type', 'Turbo']),
                                                 ('Numeric',
                                                  Pipeline(steps=[('polynomial',
                                                                   PolynomialFeatures(include_bias=False)),
                                                                  ('Scale',
                                                                   StandardScaler())]),
                                                  ['Horsepower', 'Year'])])),
                ('model',
                 SGDRegressor(early_stopping=True, eta0=0.1,
                              learning_rate='adaptive', random_state=42,
                              verbose=1))])

In [21]:
model.score(X_test,y_test)

0.7724026019867128

In [22]:
joblib.dump(model,"model")

['model']